### ISSUE TITLE
Support for astral symbols

### ISSUE THREAD

**Issue by mathiasbynens** [ryanmcgrath/node-utf8#1]
This is flawed for code points greater than U+FFFF. Since there are over a million of those, it would be good to have this fixed :)

For example, for U+1D306, this library returns:

```
U+01D306: \xED\xA0\xB4\xED\xBC\x86
```

It should be `\xF0\x9D\x8C\x86`.

**Comment by ryanmcgrath** [comment]
For some reason I never closed this, haha. Your [utf8](https://www.npmjs.com/package/utf8) library is by far a more comprehensive solution, and has been for some time - created this as a stopgap measure in the early days of Node.js. I should just update the README to point to yours at some point here.
