### ISSUE TITLE
npm package name

### ISSUE THREAD

**Issue by antelle** [ryanmcgrath/node-utf8#2]
There's another package in npm which is named utf8: 
https://www.npmjs.com/package/utf8

Please publish your package with another name, there's no way to install it with npm now.

**Comment by ryanmcgrath** [comment]
@antelle that package has existed for eons last I checked and is more
comprehensive than mine, which I threw together as a stop-gap in the wee
days of Node. Really not sure I care too much unless enough others depend
on it, chances are they're better served by utf8.

On Tuesday, June 2, 2015, antelle notifications@github.com wrote:

> There's another package in npm which is named utf8:
> https://www.npmjs.com/package/utf8
> 
> Please publish your package with another name, there's no way to install
> it with npm now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ryanmcgrath/node-utf8/issues/2.

## 

Skype: ryanmcgrathr
Twitter: http://twitter.com/ryanmcgrath/
Web: http://venodesigns.net/
GitHub: http://github.com/ryanmcgrath/

**Comment by antelle** [comment]
Okay, thanks. I have initially planned to make use of your package as it suits my needs (latin and cyrillic chars) and is dramatically faster and memory efficient than currently supported utf8.js. But yes, there are issues with some characters here, so I'll try to research and fix utf8.js performance.
